"use client";

import { useState, useEffect, useCallback, useRef } from "react";

var CSS = '@import url("https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500;600;700&family=Instrument+Serif:ital@0;1&display=swap");:root{--bg0:#0a0a0f;--bg1:#111118;--bg2:#16161f;--bg3:#1c1c28;--bgi:#1a1a25;--bd:#252533;--t1:#f0eff4;--t2:#8a8a9a;--t3:#55556a;--ac:#6c5ce7;--acl:#8b7cf0;--acg:rgba(108,92,231,.15);--grn:#00d68f;--org:#f0a030;--blu:#48b0f0;--pnk:#e84393;--red:#ff6b6b}*{margin:0;padding:0;box-sizing:border-box}body{font-family:"DM Sans",sans-serif;background:var(--bg0);color:var(--t1);-webkit-font-smoothing:antialiased}::-webkit-scrollbar{width:6px}::-webkit-scrollbar-thumb{background:var(--bd);border-radius:3px}@keyframes spin{to{transform:rotate(360deg)}}@keyframes pulse{0%,100%{opacity:1}50%{opacity:.4}}@keyframes fadeIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}';

var PC={tiktok:"#ff0050",instagram:"#e84393",facebook:"#4267B2",modash:"#6366f1"};
var PN={tiktok:"TikTok Shop",instagram:"Instagram",facebook:"Facebook",modash:"Modash"};
var PURL={tiktok:"https://seller-us.tiktok.com",instagram:"https://business.facebook.com",facebook:"https://business.facebook.com",modash:"https://app.modash.io"};
var MOCK={tiktok:[{name:"Sarah Chen",handle:"@sarahfitlife",fol:"1.2M",folR:1200000,eng:"4.8%",engR:4.8,niche:"Fitness",av:"SC",sc:92,rc:["Protein timing for beginners (50K)","Morning routine update (80K)","Gym bag essentials (30K)"]},{name:"Jake Morrison",handle:"@jakereviews",fol:"890K",folR:890000,eng:"5.2%",engR:5.2,niche:"Tech",av:"JM",sc:88,rc:["iPhone 16 Pro review (120K)","Best budget earbuds (45K)"]},{name:"Luna Park",handle:"@lunaskincare",fol:"2.1M",folR:2100000,eng:"3.9%",engR:3.9,niche:"Beauty",av:"LP",sc:95,rc:["Glass skin routine (200K)","SPF myths debunked (90K)"]},{name:"Aria Nakamura",handle:"@ariastyle",fol:"1.5M",folR:1500000,eng:"4.3%",engR:4.3,niche:"Fashion",av:"AN",sc:91,rc:["Spring capsule wardrobe (70K)"]}],instagram:[{name:"Emily Rose",handle:"@emilyrosewellness",fol:"540K",folR:540000,eng:"3.7%",engR:3.7,niche:"Wellness",av:"ER",sc:84,v:true,rc:["Mindful morning routine","Adaptogens guide"]},{name:"David Kim",handle:"@davidtravels",fol:"1.8M",folR:1800000,eng:"2.9%",engR:2.9,niche:"Travel",av:"DK",sc:87,v:true,rc:["Hidden gems in Kyoto","Budget travel SE Asia"]},{name:"Priya Sharma",handle:"@priyacooks",fol:"920K",folR:920000,eng:"5.5%",engR:5.5,niche:"Food",av:"PS",sc:90,rc:["15-min weeknight dinners"]}],facebook:[{name:"Homemaker Hub",handle:"Homemaker Hub",fol:"120K",folR:120000,eng:"8.2%",engR:8.2,niche:"Home",av:"HH",sc:76,rc:[]},{name:"FitFam",handle:"FitFam Official",fol:"890K",folR:890000,eng:"5.4%",engR:5.4,niche:"Fitness",av:"FF",sc:80,rc:[]}],modash:[{name:"Zara Williams",handle:"@zarastyle",fol:"780K",folR:780000,eng:"5.1%",engR:5.1,niche:"Fashion",av:"ZW",sc:89,ap:"instagram",rc:["OOTD compilation"]},{name:"Tom Fitness",handle:"@tomfitpro",fol:"1.4M",folR:1400000,eng:"4.6%",engR:4.6,niche:"Fitness",av:"TF",sc:93,ap:"tiktok",rc:["30-day challenge results"]},{name:"Nia Beauty",handle:"@niaglows",fol:"420K",folR:420000,eng:"6.9%",engR:6.9,niche:"Beauty",av:"NB",sc:86,ap:"instagram",rc:["Skincare routine for oily skin"]}]};
var iS={width:"100%",padding:"10px 14px",background:"var(--bgi)",border:"1px solid var(--bd)",borderRadius:8,color:"var(--t1)",fontSize:13,outline:"none",fontFamily:"'DM Sans',sans-serif"};
var lS={display:"block",fontSize:10,fontWeight:600,textTransform:"uppercase",letterSpacing:".08em",color:"var(--t3)",marginBottom:6};
var bS={border:"none",borderRadius:10,fontSize:14,fontWeight:600,cursor:"pointer",fontFamily:"'DM Sans',sans-serif",padding:"10px 24px"};
var TTC=["","Womenswear","Menswear","Beauty & Personal Care","Food & Beverages","Health","Tech & Electronics","Home & Garden","Baby & Kids","Sports & Outdoors"];var TTCL=["Any","Womenswear","Menswear","Beauty","Food","Health","Tech","Home","Baby","Sports"];var TTF=["Any","1K-10K","10K-50K","50K-100K","100K-500K","500K-1M","1M+"];var TTCM=["Any","5%+","10%+","15%+","20%+"];var TTCO=["Any","Shoppable Video","LIVE","Both"];var TTR=["Any","$100+","$500+","$1K+","$5K+","$10K+"];var TTU=["Any","10+","50+","100+","500+","1K+"];var TTV=["Any","1K+","5K+","10K+","50K+","100K+"];var TTE=["Any","1%+","2%+","3%+","5%+","8%+","10%+"];
var IGI=[{v:"BEAUTY",l:"Beauty"},{v:"FASHION",l:"Fashion"},{v:"FITNESS",l:"Fitness"},{v:"FOOD",l:"Food"},{v:"TECH",l:"Tech"},{v:"SPORTS",l:"Sports"},{v:"TRAVEL",l:"Travel"},{v:"HOME",l:"Home"},{v:"PETS",l:"Pets"},{v:"EDU",l:"Education"}];var IGA=["18-24","25-34","35-44","45-54","55-64","65+"];var IGF2=["Any","10K+","25K+","50K+","75K+","100K+"];var IGE=["Any","0","2K","10K","50K","100K"];
var ST={pending:{c:"var(--org)",bg:"rgba(240,160,48,.1)",l:"Pending"},interested:{c:"var(--grn)",bg:"rgba(0,214,143,.1)",l:"Interested"},declined:{c:"var(--red)",bg:"rgba(255,107,107,.1)",l:"Declined"},no_reply:{c:"var(--t3)",bg:"var(--bg3)",l:"No Reply"}};
var STAGES=["interested","negotiating","agreed","active"];var STAGE_L={interested:"Interested",negotiating:"Negotiating",agreed:"Agreed",active:"Active"};var STAGE_C={interested:"var(--grn)",negotiating:"var(--org)",agreed:"var(--blu)",active:"var(--ac)"};

function Tag(p){return <span style={{fontSize:10,fontWeight:600,padding:"3px 8px",borderRadius:5,background:p.bg||p.color+"18",color:p.color,whiteSpace:"nowrap"}}>{p.children}</span>;}
function Ck(p){return <div onClick={function(e){e.stopPropagation();p.flip();}} style={{width:18,height:18,borderRadius:4,border:p.on?"2px solid var(--ac)":"2px solid var(--bd)",background:p.on?"var(--ac)":"transparent",display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer",flexShrink:0}}>{p.on?<svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="3" strokeLinecap="round"><path d="M20 6L9 17l-5-5"/></svg>:null}</div>;}
function Sel(p){return <select value={p.value} onChange={function(e){p.onChange(e.target.value);}} style={{...iS,cursor:"pointer"}}>{(p.labs||p.opts).map(function(l,i){return <option key={i} value={p.opts[i]}>{l}</option>;})}</select>;}
function Tg(p){return <div onClick={p.flip} style={{display:"flex",alignItems:"center",gap:8,cursor:"pointer",fontSize:12,color:"var(--t2)"}}><div style={{width:34,height:18,borderRadius:9,background:p.on?"var(--ac)":"var(--bd)",position:"relative",flexShrink:0}}><div style={{width:14,height:14,borderRadius:"50%",background:"#fff",position:"absolute",top:2,left:p.on?18:2,transition:"left .2s"}}/></div>{p.label}</div>;}
function Ch(p){return <div style={{display:"flex",flexWrap:"wrap",gap:6}}>{p.opts.map(function(o){var v2=typeof o==="string"?o:o.v,l2=typeof o==="string"?o:o.l,a2=p.sel.includes(v2);return <button key={v2} onClick={function(){p.tog(v2);}} style={{padding:"5px 12px",borderRadius:6,fontSize:12,fontWeight:500,border:a2?"1px solid var(--ac)":"1px solid var(--bd)",background:a2?"var(--acg)":"transparent",color:a2?"var(--acl)":"var(--t3)",cursor:"pointer",fontFamily:"'DM Sans',sans-serif"}}>{l2}</button>;})}</div>;}
function Rw(p){return <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(200px,1fr))",gap:14,marginBottom:16}}>{p.children}</div>;}
function Fl(p){return <div><label style={lS}>{p.label}</label>{p.children}</div>;}
function Dv(p){return <div style={{fontSize:13,fontWeight:600,color:"var(--t2)",marginBottom:14,paddingTop:16,marginTop:8,borderTop:"1px solid var(--bd)",display:"flex",alignItems:"center",gap:8}}>{p.label}{p.tag?<Tag color={p.tc||"var(--ac)"}>{p.tag}</Tag>:null}</div>;}
// FIX #18,28: Confirmation modal
function Modal(p){if(!p.show)return null;return <div style={{position:"fixed",top:0,left:0,right:0,bottom:0,background:"rgba(0,0,0,.6)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:100}} onClick={p.onCancel}><div style={{background:"var(--bg2)",border:"1px solid var(--bd)",borderRadius:16,padding:32,maxWidth:440,width:"100%"}} onClick={function(e){e.stopPropagation();}}><h3 style={{fontSize:18,fontWeight:600,marginBottom:12}}>{p.title}</h3><p style={{fontSize:14,color:"var(--t2)",marginBottom:24,lineHeight:1.5}}>{p.body}</p><div style={{display:"flex",justifyContent:"flex-end",gap:12}}><button onClick={p.onCancel} style={{...bS,padding:"8px 20px",background:"transparent",border:"1px solid var(--bd)",color:"var(--t2)"}}>Cancel</button><button onClick={p.onConfirm} style={{...bS,padding:"8px 20px",background:p.danger?"var(--red)":"var(--grn)",color:p.danger?"#fff":"#000"}}>{p.confirmLabel||"Confirm"}</button></div></div></div>;}

// FIX #1,2: Login with register toggle + forgot password
function Login(p){var _l=useState(false),ld=_l[0],sLd=_l[1];var _s=useState(false),sh=_s[0],sSh=_s[1];var _mode=useState("login"),mode=_mode[0],sMode=_mode[1];var _e=useState(""),em=_e[0],sEm=_e[1];var _pw=useState(""),pw=_pw[0],sPw=_pw[1];var _err=useState(""),err=_err[0],sErr=_err[1];
useEffect(function(){setTimeout(function(){sSh(true);},100);},[]);
var _sent=useState(false),resetSent=_sent[0],sResetSent=_sent[1];
var submit=function(){sErr("");if(!em||!em.includes("@")){sErr("Please enter a valid email");return;}if(mode==="forgot"){sLd(true);setTimeout(function(){sLd(false);sResetSent(true);},1000);return;}if(!pw||pw.length<6){sErr(mode==="login"?"Please enter your password":"Password must be at least 6 characters");return;}sLd(true);setTimeout(p.onIn,1200);};
return(<div style={{minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",background:"var(--bg0)"}}><div style={{width:"100%",maxWidth:420,padding:"0 24px",opacity:sh?1:0,transform:sh?"none":"translateY(20px)",transition:"all .8s cubic-bezier(.16,1,.3,1)"}}><div style={{textAlign:"center",marginBottom:48}}><div style={{display:"inline-flex",alignItems:"center",gap:10,marginBottom:32}}><div style={{width:40,height:40,borderRadius:12,background:"linear-gradient(135deg,var(--ac),#e84393)",display:"flex",alignItems:"center",justifyContent:"center"}}><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8Z" fill="#fff" opacity=".9"/></svg></div><span style={{fontSize:22,fontWeight:700}}>OutreachAI</span></div><h1 style={{fontFamily:"'Instrument Serif',serif",fontSize:38,fontWeight:400,marginBottom:12}}>{mode==="login"?"Welcome back":mode==="register"?"Create account":"Reset password"}</h1><p style={{color:"var(--t2)",fontSize:15}}>{mode==="login"?"Sign in to your account":mode==="register"?"Start finding creators today":"Enter your email to receive a reset link"}</p></div>
<div style={{display:"flex",flexDirection:"column",gap:16}}>
{mode!=="forgot"?<React.Fragment><div><label style={lS}>Email</label><input value={em} onChange={function(e){sEm(e.target.value);sErr("");}} placeholder="you@company.com" style={{...iS,fontSize:15,padding:"14px 16px"}}/></div><div><label style={lS}>Password</label><input value={pw} onChange={function(e){sPw(e.target.value);sErr("");}} type="password" placeholder="••••••••" style={{...iS,fontSize:15,padding:"14px 16px"}}/></div>{mode==="login"?<button onClick={function(){sMode("forgot");}} style={{background:"none",border:"none",color:"var(--acl)",fontSize:13,cursor:"pointer",textAlign:"right",fontFamily:"'DM Sans',sans-serif"}}>Forgot password?</button>:null}</React.Fragment>
:<div><label style={lS}>Email</label><input value={em} onChange={function(e){sEm(e.target.value);sErr("");}} placeholder="you@company.com" style={{...iS,fontSize:15,padding:"14px 16px"}}/>{resetSent?<div style={{marginTop:12,fontSize:13,color:"var(--grn)",padding:"10px 14px",background:"rgba(0,214,143,.08)",borderRadius:8}}>Reset link sent to {em}. Check your inbox.</div>:null}</div>}
{err?<div style={{fontSize:13,color:"var(--red)",padding:"8px 12px",background:"rgba(255,107,107,.08)",borderRadius:8}}>{err}</div>:null}
{!resetSent?<button onClick={submit} style={{...bS,width:"100%",padding:14,marginTop:4,background:ld?"var(--bg2)":"linear-gradient(135deg,var(--ac),#8b5cf6)",color:"#fff",fontSize:15}}>{ld?"Please wait...":(mode==="login"?"Sign in":mode==="register"?"Create account":"Send reset link")}</button>:null}
<div style={{textAlign:"center",fontSize:13,color:"var(--t3)"}}>{mode==="login"?<span>No account? <button onClick={function(){sMode("register");sErr("");sLd(false);sPw("");}} style={{background:"none",border:"none",color:"var(--acl)",cursor:"pointer",fontFamily:"'DM Sans',sans-serif",fontSize:13}}>Sign up</button></span>:<span><button onClick={function(){sMode("login");sErr("");sLd(false);sPw("");sResetSent(false);}} style={{background:"none",border:"none",color:"var(--acl)",cursor:"pointer",fontFamily:"'DM Sans',sans-serif",fontSize:13}}>Back to sign in</button></span>}</div>
</div></div></div>);}

// FIX #27: Sidebar with logout
function Side(p){var cc=Object.values(p.sess).filter(Boolean).length;var pend=p.outreach.filter(function(o){return o.replyStatus==="pending"||o.replyStatus==="no_reply";}).length;
return(<div style={{width:240,minHeight:"100vh",background:"var(--bg1)",borderRight:"1px solid var(--bd)",padding:"20px 12px",display:"flex",flexDirection:"column",position:"fixed",left:0,top:0,zIndex:10}}><div style={{display:"flex",alignItems:"center",gap:10,padding:"4px 10px",marginBottom:20}}><div style={{width:32,height:32,borderRadius:8,background:"linear-gradient(135deg,var(--ac),#e84393)",display:"flex",alignItems:"center",justifyContent:"center"}}><svg width="15" height="15" viewBox="0 0 24 24" fill="none"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8Z" fill="#fff" opacity=".9"/></svg></div><span style={{fontSize:16,fontWeight:700}}>OutreachAI</span></div>
{/* FIX #26: Cowork status from prop */}
<div style={{display:"flex",alignItems:"center",gap:6,padding:"6px 12px",borderRadius:8,background:p.coworkOn?"rgba(0,214,143,.08)":"rgba(255,107,107,.08)",border:"1px solid "+(p.coworkOn?"rgba(0,214,143,.25)":"rgba(255,107,107,.25)"),marginBottom:20,marginLeft:4,marginRight:4}}><div style={{width:7,height:7,borderRadius:"50%",background:p.coworkOn?"var(--grn)":"var(--red)",animation:p.coworkOn?"pulse 2s infinite":"none"}}/><span style={{fontSize:11,fontWeight:600,color:p.coworkOn?"var(--grn)":"var(--red)"}}>{p.coworkOn?"Cowork Active":"Cowork Off"}</span></div>
{[["programs","Programs"],["discover","Discover"],["outreach","Outreach"],["sessions","Sessions"]].map(function(item){var id=item[0],l=item[1],dis=(id==="discover"||id==="outreach")&&!p.progs.length,a=p.pg===id;return <button key={id} onClick={function(){if(!dis)p.nav(id);}} style={{display:"flex",alignItems:"center",gap:10,padding:"10px 12px",border:"none",borderRadius:8,background:a?"var(--acg)":"transparent",color:dis?"var(--t3)":a?"var(--acl)":"var(--t2)",fontSize:14,fontWeight:a?600:400,cursor:dis?"not-allowed":"pointer",fontFamily:"'DM Sans',sans-serif",textAlign:"left",width:"100%",opacity:dis?.5:1,marginBottom:2}}>{l}{id==="outreach"&&pend>0?<span style={{marginLeft:"auto",fontSize:10,fontWeight:700,padding:"1px 7px",borderRadius:10,background:"rgba(240,160,48,.15)",color:"var(--org)"}}>{pend}</span>:null}{id==="sessions"&&cc>0?<span style={{marginLeft:"auto",fontSize:10,fontWeight:700,padding:"1px 7px",borderRadius:10,background:"rgba(0,214,143,.15)",color:"var(--grn)"}}>{cc}/4</span>:null}</button>;})}
{p.progs.length>0?<div><div style={{fontSize:10,fontWeight:600,textTransform:"uppercase",letterSpacing:".1em",color:"var(--t3)",padding:"0 10px",marginTop:28,marginBottom:8}}>Programs</div>{p.progs.map(function(pr,i){return <button key={pr.id} onClick={function(){p.nav("discover",i);}} style={{display:"flex",alignItems:"center",gap:8,padding:"8px 12px",border:"none",borderRadius:8,background:p.sel===i&&p.pg==="discover"?"var(--acg)":"transparent",color:p.sel===i&&p.pg==="discover"?"var(--t1)":"var(--t2)",fontSize:13,cursor:"pointer",fontFamily:"'DM Sans',sans-serif",textAlign:"left",width:"100%",marginBottom:2}}><div style={{width:8,height:8,borderRadius:"50%",background:["var(--ac)","var(--grn)","var(--org)","var(--pnk)"][i%4],flexShrink:0}}/>{pr.name}</button>;})}</div>:null}
{/* FIX #27: Logout */}
<div style={{marginTop:"auto",padding:"12px 10px",borderTop:"1px solid var(--bd)"}}><div style={{display:"flex",alignItems:"center",gap:10}}><div style={{width:32,height:32,borderRadius:"50%",background:"linear-gradient(135deg,var(--ac),#e84393)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:13,fontWeight:600}}>JD</div><div style={{flex:1}}><div style={{fontSize:13,fontWeight:500}}>John Doe</div><div style={{fontSize:11,color:"var(--t3)"}}>Pro Plan</div></div><button onClick={p.onLogout} style={{background:"none",border:"none",color:"var(--t3)",cursor:"pointer",fontSize:12,fontFamily:"'DM Sans',sans-serif"}}>Logout</button></div></div></div>);}

// FIX #6: Sessions with open links
function Sessions(p){var pl=[{id:"tiktok",name:"TikTok Shop",desc:"Affiliate Center > Find Creators",color:"#ff0050",url:"https://seller-us.tiktok.com"},{id:"instagram",name:"Instagram",desc:"Creator Marketplace",color:"#e84393",url:"https://business.facebook.com"},{id:"facebook",name:"Facebook",desc:"Creator Discovery",color:"#4267B2",url:"https://business.facebook.com"},{id:"modash",name:"Modash",desc:"Discovery search",color:"#6366f1",url:"https://app.modash.io"}];
return(<div><h1 style={{fontFamily:"'Instrument Serif',serif",fontSize:32,fontWeight:400,marginBottom:6}}>Browser Sessions</h1><p style={{color:"var(--t2)",fontSize:14,marginBottom:28}}>Log into each platform in a Chrome tab. Claude Cowork navigates them.</p>
{/* FIX #4: Onboarding hint if no sessions active */}
{Object.values(p.sess).filter(Boolean).length===0?<div style={{background:"var(--acg)",border:"1px solid rgba(108,92,231,.3)",borderRadius:14,padding:20,marginBottom:28}}><div style={{fontSize:14,fontWeight:600,color:"var(--acl)",marginBottom:6}}>Getting started</div><div style={{fontSize:13,color:"var(--t2)",lineHeight:1.6}}>1. Click "Open" on each platform below to open it in a new tab. 2. Log in with your account. 3. Click "Mark Ready" here. 4. Create your first program to start finding creators.</div></div>:null}
<div style={{display:"flex",flexDirection:"column",gap:14}}>{pl.map(function(x){var on=p.sess[x.id];return(<div key={x.id} style={{background:"var(--bg2)",border:"1px solid "+(on?x.color+"40":"var(--bd)"),borderRadius:14,padding:20,display:"flex",justifyContent:"space-between",alignItems:"center",gap:12}}>
<div style={{flex:1}}><div style={{fontSize:16,fontWeight:600,marginBottom:4}}>{x.name}</div><div style={{fontSize:13,color:"var(--t3)"}}>{x.desc}</div></div>
<div style={{display:"flex",gap:8,flexShrink:0}}><a href={x.url} target="_blank" rel="noopener noreferrer" style={{padding:"8px 14px",border:"1px solid var(--bd)",borderRadius:8,background:"transparent",color:"var(--t2)",fontSize:12,fontWeight:600,textDecoration:"none",fontFamily:"'DM Sans',sans-serif"}}>Open</a>
<button onClick={function(){p.toggle(x.id);}} style={{padding:"8px 16px",border:"1px solid "+(on?x.color+"40":"var(--bd)"),borderRadius:8,background:on?x.color+"12":"transparent",color:on?x.color:"var(--t2)",fontSize:12,fontWeight:600,cursor:"pointer",fontFamily:"'DM Sans',sans-serif"}}>{on?"Ready ✓":"Mark Ready"}</button></div></div>);})}</div></div>);}

function Progs(p){
// FIX #5: Nudge user to sessions if none active
var noSess=Object.values(p.sess).filter(Boolean).length===0;
// FIX #28: delete confirm state
var _dc=useState(null),dc=_dc[0],sDc=_dc[1];
return(<div><Modal show={dc!==null} title="Delete Program?" body={"This will permanently delete \""+((p.progs[dc]||{}).name||"")+"\" and all its prospects and outreach history."} danger={true} confirmLabel="Delete" onCancel={function(){sDc(null);}} onConfirm={function(){p.onDelete(dc);sDc(null);}}/>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:36}}><h1 style={{fontFamily:"'Instrument Serif',serif",fontSize:32,fontWeight:400}}>Your Programs</h1><button onClick={function(){if(noSess){p.nav("sessions");}else{p.onCreate();}}} style={{...bS,background:"linear-gradient(135deg,var(--ac),#8b5cf6)",color:"#fff"}}>{noSess?"Set Up Sessions First":"+ New Program"}</button></div>
{p.progs.length===0?<div style={{textAlign:"center",padding:"80px 20px",border:"1px dashed var(--bd)",borderRadius:16,background:"var(--bg2)"}}><h3 style={{fontSize:18,fontWeight:600,marginBottom:8}}>No programs yet</h3><p style={{color:"var(--t2)",fontSize:14,maxWidth:360,margin:"0 auto 24px"}}>{noSess?"First, set up your browser sessions, then create a program.":"Create a program to define your audience."}</p><button onClick={function(){if(noSess)p.nav("sessions");else p.onCreate();}} style={{...bS,background:"var(--ac)",color:"#fff"}}>{noSess?"Go to Sessions":"Create First Program"}</button></div>
:<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(320px,1fr))",gap:16}}>{p.progs.map(function(pr,i){return(<div key={pr.id} style={{padding:24,background:"var(--bg2)",border:"1px solid var(--bd)",borderRadius:14,cursor:"pointer",position:"relative",overflow:"hidden"}} onClick={function(){p.onSel(i);}} onMouseEnter={function(e){e.currentTarget.style.borderColor="var(--ac)";}} onMouseLeave={function(e){e.currentTarget.style.borderColor="var(--bd)";}}>
<div style={{position:"absolute",top:0,left:0,right:0,height:3,background:"linear-gradient(90deg,"+["var(--ac)","var(--grn)","var(--org)","var(--pnk)"][i%4]+",transparent)"}}/>
<div style={{display:"flex",justifyContent:"space-between",marginBottom:8}}><h3 style={{fontSize:17,fontWeight:600}}>{pr.name}</h3><div style={{display:"flex",gap:6}}><Tag color="var(--grn)" bg="rgba(0,214,143,.1)">Active</Tag><button onClick={function(e){e.stopPropagation();sDc(i);}} style={{background:"none",border:"none",color:"var(--t3)",cursor:"pointer",fontSize:14,padding:"0 4px"}} title="Delete program">x</button></div></div>
<div style={{display:"flex",gap:6,flexWrap:"wrap",marginBottom:14}}>{pr.platforms.map(function(pl){return <span key={pl} style={{fontSize:12,padding:"4px 10px",borderRadius:6,background:PC[pl]+"15",color:PC[pl],fontWeight:500}}>{PN[pl]}</span>;})}</div>
<div style={{display:"flex",gap:20,paddingTop:14,borderTop:"1px solid var(--bd)"}}>{[["Prospects",pr.prospects],["Contacted",pr.contacted],["Interested",pr.interested||0]].map(function(x,j){return <div key={j}><div style={{fontSize:18,fontWeight:700}}>{x[1]}</div><div style={{fontSize:11,color:"var(--t3)"}}>{x[0]}</div></div>;})}</div></div>);})}</div>}</div>);}

// FIX #10: Step labels in Create
function Crt(p){var _n=useState(""),nm=_n[0],sNm=_n[1];var _p2=useState([]),pl=_p2[0],sPl=_p2[1];var _s=useState(1),st=_s[0],sSt=_s[1];var _f=useState(""),ft=_f[0],sFt=_f[1];
var _fi=useState({ttCat:"",ttFol:"Any",ttComm:"Any",ttCont:"Any",ttAgn:"Any",ttFG:false,ttNI:false,ttCP:false,ttFA:[],ttFGn:"Any",ttRev:"Any",ttUS:"Any",ttAV:"Any",ttEng:"Any",igFol:"Any",igCC:"",igCG:"Any",igCA:[],igInt:[],igMnE:"Any",igMxE:"Any",igRR:"Any",fbQ:"",fbAD:"Any",fbEng:"Any",mdPlat:"All",mdFol:"Any",mdEng:"Any",mdLoc:"",mdQ:"",mdFF:false}),f=_fi[0],sF=_fi[1];
var up=useCallback(function(k,v){sF(function(prev){return{...prev,[k]:v};});},[]);var ta=function(k,v){sF(function(prev){var a=prev[k];return{...prev,[k]:a.includes(v)?a.filter(function(x){return x!==v;}):[...a,v]};});};
useEffect(function(){if(pl.length>0&&(!ft||!pl.includes(ft)))sFt(pl[0]);},[pl,ft]);
var tp=function(v){if(!p.sess[v])return;sPl(function(prev){return prev.includes(v)?prev.filter(function(x){return x!==v;}):[...prev,v];});};var cn=st===1?nm&&pl.length>0:true;
return(<div>
{/* FIX #29: Back breadcrumb */}
<button onClick={p.onCancel} style={{background:"none",border:"none",color:"var(--t2)",fontSize:13,cursor:"pointer",marginBottom:24,fontFamily:"'DM Sans',sans-serif"}}>{"<-"} Back to Programs</button>
<div style={{display:"flex",alignItems:"center",gap:16,marginBottom:36}}><h1 style={{fontFamily:"'Instrument Serif',serif",fontSize:32,fontWeight:400}}>Create Program</h1>
{/* FIX #10: Step labels */}
<div style={{display:"flex",gap:8,marginLeft:"auto"}}>{[["1","Details"],["2","Filters"]].map(function(x){var active=+x[0]<=st;return <div key={x[0]} style={{display:"flex",alignItems:"center",gap:4}}><div style={{width:active?24:8,height:8,borderRadius:4,background:active?"var(--ac)":"var(--bd)",transition:"all .3s"}}/>{active?<span style={{fontSize:11,color:"var(--acl)",fontWeight:600}}>{x[1]}</span>:null}</div>;})}</div></div>
{st===1?<div style={{background:"var(--bg2)",border:"1px solid var(--bd)",borderRadius:16,padding:32}}><h2 style={{fontSize:18,fontWeight:600,marginBottom:28}}>Details & Platforms</h2><div style={{marginBottom:28}}><label style={lS}>Program Name</label><input value={nm} onChange={function(e){sNm(e.target.value);}} placeholder="e.g. Summer Fitness Campaign" style={{...iS,maxWidth:480}}/></div>
<label style={lS}>Platforms</label><div style={{display:"flex",gap:12,flexWrap:"wrap"}}>{["tiktok","instagram","facebook","modash"].map(function(k){var a=pl.includes(k),ready=p.sess[k];return <button key={k} onClick={function(){tp(k);}} style={{display:"flex",alignItems:"center",gap:10,padding:"14px 20px",borderRadius:12,fontSize:14,fontWeight:500,border:a?"1px solid "+PC[k]:"1px solid var(--bd)",background:a?PC[k]+"12":"var(--bgi)",color:a?PC[k]:ready?"var(--t2)":"var(--t3)",cursor:ready?"pointer":"not-allowed",fontFamily:"'DM Sans',sans-serif",minWidth:160,opacity:ready?1:.4}}>{PN[k]}</button>;})}</div></div>
:<div style={{background:"var(--bg2)",border:"1px solid var(--bd)",borderRadius:16,padding:32}}><h2 style={{fontSize:18,fontWeight:600,marginBottom:24}}>Filters</h2>
<div style={{display:"flex",gap:4,padding:4,background:"var(--bg0)",borderRadius:10,marginBottom:24,width:"fit-content",border:"1px solid var(--bd)"}}>{pl.map(function(pp){var a=ft===pp;return <button key={pp} onClick={function(){sFt(pp);}} style={{padding:"8px 16px",border:"none",borderRadius:7,background:a?"var(--bg2)":"transparent",color:a?"var(--t1)":"var(--t3)",fontSize:13,fontWeight:a?600:400,cursor:"pointer",fontFamily:"'DM Sans',sans-serif"}}>{PN[pp]}</button>;})}</div>
<div style={{padding:20,background:"var(--bg0)",borderRadius:12,border:"1px solid var(--bd)"}}>
{ft==="tiktok"?<div><Rw><Fl label="Category"><Sel value={f.ttCat} onChange={function(v){up("ttCat",v);}} opts={TTC} labs={TTCL}/></Fl><Fl label="Followers"><Sel value={f.ttFol} onChange={function(v){up("ttFol",v);}} opts={TTF}/></Fl><Fl label="Commission"><Sel value={f.ttComm} onChange={function(v){up("ttComm",v);}} opts={TTCM}/></Fl><Fl label="Content"><Sel value={f.ttCont} onChange={function(v){up("ttCont",v);}} opts={TTCO}/></Fl></Rw><Rw><Fl label="Agency"><Sel value={f.ttAgn} onChange={function(v){up("ttAgn",v);}} opts={["Any","Independent","Agency"]}/></Fl><div style={{display:"flex",flexDirection:"column",gap:10}}><Tg on={f.ttFG} flip={function(){up("ttFG",!f.ttFG);}} label="Fast Growing"/><Tg on={f.ttNI} flip={function(){up("ttNI",!f.ttNI);}} label="Not invited 90d"/><Tg on={f.ttCP} flip={function(){up("ttCP",!f.ttCP);}} label="Category Pro"/></div></Rw><Dv label="Demographics" tag="Audience" tc="var(--org)"/><Rw><Fl label="Age"><Ch opts={["13-17","18-24","25-34","35-44","45-54","55+"]} sel={f.ttFA} tog={function(v){ta("ttFA",v);}}/></Fl><Fl label="Gender"><Sel value={f.ttFGn} onChange={function(v){up("ttFGn",v);}} opts={["Any","Male","Female"]}/></Fl></Rw><Dv label="Performance" tag="30 days" tc="var(--grn)"/><Rw><Fl label="Revenue"><Sel value={f.ttRev} onChange={function(v){up("ttRev",v);}} opts={TTR}/></Fl><Fl label="Units"><Sel value={f.ttUS} onChange={function(v){up("ttUS",v);}} opts={TTU}/></Fl><Fl label="Views"><Sel value={f.ttAV} onChange={function(v){up("ttAV",v);}} opts={TTV}/></Fl><Fl label="Engagement"><Sel value={f.ttEng} onChange={function(v){up("ttEng",v);}} opts={TTE}/></Fl></Rw></div>:null}
{ft==="instagram"?<div><Rw><Fl label="Followers"><Sel value={f.igFol} onChange={function(v){up("igFol",v);}} opts={IGF2}/></Fl><Fl label="Country"><input value={f.igCC} onChange={function(e){up("igCC",e.target.value);}} placeholder="US, GB" style={iS}/></Fl><Fl label="Gender"><Sel value={f.igCG} onChange={function(v){up("igCG",v);}} opts={["Any","Male","Female"]}/></Fl></Rw><Fl label="Interests"><Ch opts={IGI} sel={f.igInt} tog={function(v){ta("igInt",v);}}/></Fl><Dv label="Engagement" tag="First-party" tc="var(--grn)"/><Rw><Fl label="Min Engaged"><Sel value={f.igMnE} onChange={function(v){up("igMnE",v);}} opts={IGE}/></Fl><Fl label="Reels Rate"><Sel value={f.igRR} onChange={function(v){up("igRR",v);}} opts={["Any","1%+","2%+","3%+","5%+","8%+"]}/></Fl></Rw></div>:null}
{ft==="facebook"?<div><Rw><Fl label="Keywords"><input value={f.fbQ} onChange={function(e){up("fbQ",e.target.value);}} placeholder="fitness" style={iS}/></Fl><Fl label="Age"><Sel value={f.fbAD} onChange={function(v){up("fbAD",v);}} opts={["Any","18-24","25-34","35-44","45+"]}/></Fl></Rw></div>:null}
{ft==="modash"?<div><Rw><Fl label="Platform"><Sel value={f.mdPlat} onChange={function(v){up("mdPlat",v);}} opts={["All","TikTok","Instagram","YouTube"]}/></Fl><Fl label="Followers"><Sel value={f.mdFol} onChange={function(v){up("mdFol",v);}} opts={["Any","1K+","10K+","50K+","100K+","1M+"]}/></Fl><Fl label="Engagement"><Sel value={f.mdEng} onChange={function(v){up("mdEng",v);}} opts={["Any","1%+","2%+","3%+","5%+"]}/></Fl></Rw><Rw><Fl label="Location"><input value={f.mdLoc} onChange={function(e){up("mdLoc",e.target.value);}} placeholder="US" style={iS}/></Fl><Fl label="Niche"><input value={f.mdQ} onChange={function(e){up("mdQ",e.target.value);}} placeholder="fitness" style={iS}/></Fl></Rw><Tg on={f.mdFF} flip={function(){up("mdFF",!f.mdFF);}} label="Exclude fake followers"/></div>:null}
</div></div>}
<div style={{display:"flex",justifyContent:"flex-end",gap:12,marginTop:24}}>{st>1?<button onClick={function(){sSt(1);}} style={{...bS,border:"1px solid var(--bd)",background:"transparent",color:"var(--t2)"}}>Back</button>:null}<button onClick={function(){if(st<2)sSt(2);else p.onSave({id:"prog_"+Date.now(),name:nm,platforms:pl,filters:f,prospects:0,contacted:0,interested:0});}} disabled={!cn} style={{...bS,background:cn?"linear-gradient(135deg,var(--ac),#8b5cf6)":"var(--bgi)",color:cn?"#fff":"var(--t3)",cursor:cn?"pointer":"not-allowed"}}>{st<2?"Next: Filters":"Launch"}</button></div></div>);}

// FIX #11,12,13,14,15,16,29: Discover with sort, search, cancel, summary, detail actions, contacted marker, breadcrumb
function Disc(p){var _a=useState(p.prog.platforms[0]),aP=_a[0],sAP=_a[1];var _pr=useState({}),pros=_pr[0],sPros=_pr[1];var _sc=useState(false),scan=_sc[0],sScan=_sc[1];var _pc=useState(0),pct=_pc[0],sPct=_pc[1];var _ck=useState({}),checked=_ck[0],sCk=_ck[1];var _lg=useState([]),logs=_lg[0],sLogs=_lg[1];var timersRef=useRef([]);
var _detail=useState(null),detail=_detail[0],sDetail=_detail[1];var _skipped=useState({}),skipped=_skipped[0],sSkipped=_skipped[1];var _showSk=useState(false),showSk=_showSk[0],sShowSk=_showSk[1];
var _sort=useState("score"),sortBy=_sort[0],sSort=_sort[1];var _search=useState(""),search=_search[0],sSearch=_search[1];var _summary=useState(null),summary=_summary[0],sSummary=_summary[1];
var otherO={};p.allOutreach.forEach(function(o){if(o.programId!==p.prog.id)otherO[o.handle+"|"+o.platform]=o;});
var thisO={};p.allOutreach.forEach(function(o){if(o.programId===p.prog.id){thisO[o.handle+"|"+o.platform]=o;}}); 

var cancelScan=function(){timersRef.current.forEach(clearTimeout);timersRef.current=[];sScan(false);var count=Object.values(pros).reduce(function(s,a){return s+a.length;},0);if(count>0)p.onProspectsFound(count);var summ=[];p.prog.platforms.forEach(function(plat){var c3=(pros[plat]||[]).length;if(c3>0)summ.push(PN[plat]+": "+c3);});if(summ.length>0)sSummary(summ.join(" · ")+" (cancelled)");};
var runScan=function(){sScan(true);sPct(0);sPros({});sCk({});sLogs([]);sDetail(null);sSummary(null);timersRef.current.forEach(clearTimeout);timersRef.current=[];var done=false;var pi=setInterval(function(){if(done)return;sPct(function(prev){if(prev>=100){done=true;clearInterval(pi);return 100;}return prev+Math.random()*6+2;});},250);timersRef.current.push(pi);
p.prog.platforms.forEach(function(plat,idx){timersRef.current.push(setTimeout(function(){sLogs(function(prev){return prev.concat([{msg:"Scraping "+PN[plat]+"...",c:PC[plat]}]);});},500+idx*2500));var mockList=MOCK[plat]||[];mockList.forEach(function(pr,i){timersRef.current.push(setTimeout(function(){sPros(function(prev){return{...prev,[plat]:(prev[plat]||[]).concat([pr])};});},1500+idx*2500+i*400));});});
timersRef.current.push(setTimeout(function(){sScan(false);var tot=0;var summ=[];p.prog.platforms.forEach(function(plat){var c3=(MOCK[plat]||[]).length;tot+=c3;summ.push(PN[plat]+": "+c3);});sSummary(summ.join(" · "));p.onProspectsFound(tot);},p.prog.platforms.length*2500+2000));};
useEffect(function(){return function(){timersRef.current.forEach(clearTimeout);};},[]);
var rawCur=pros[aP]||[];
// FIX #16: Mark already-contacted in this program
// FIX #11: Sort
var sorted=[].concat(rawCur);if(sortBy==="score")sorted.sort(function(a,b){return b.sc-a.sc;});if(sortBy==="followers")sorted.sort(function(a,b){return(b.folR||0)-(a.folR||0);});if(sortBy==="engagement")sorted.sort(function(a,b){return(b.engR||0)-(a.engR||0);});if(sortBy==="name")sorted.sort(function(a,b){return a.name.localeCompare(b.name);});
// FIX #12: Search
var cur=sorted.filter(function(pr){if(!showSk&&skipped[pr.handle+"|"+aP])return false;if(search){var s=search.toLowerCase();return pr.name.toLowerCase().indexOf(s)>=0||pr.handle.toLowerCase().indexOf(s)>=0||pr.niche.toLowerCase().indexOf(s)>=0;}return true;});
var tot=Object.values(pros).reduce(function(s,a){return s+a.length;},0);var skCount=Object.values(skipped).filter(Boolean).length;var selCount=Object.values(checked).filter(Boolean).length;
var selectableCur=cur.filter(function(pr){var k=pr.handle+"|"+aP;return!(thisO[k]||thisO[pr.handle+"|"+(pr.ap||aP)]);});
var allChecked=selectableCur.length>0&&selectableCur.every(function(pr){return checked[pr.handle+"|"+aP];});
var toggleAll=function(){var next={...checked};cur.forEach(function(pr){var k=pr.handle+"|"+aP;var alreadySent=thisO[k]||thisO[pr.handle+"|"+(pr.ap||aP)];if(!alreadySent)next[k]=!allChecked;});sCk(next);};
var getSelected=function(){var sel=[];Object.entries(checked).forEach(function(entry){if(!entry[1])return;var pts=entry[0].split("|");Object.keys(pros).forEach(function(plat){(pros[plat]||[]).forEach(function(pr){if(pr.handle===pts[0]&&plat===pts[1])sel.push({...pr,platform:pr.ap||plat});});});});return sel;};
var selDupes=getSelected().filter(function(s){return otherO[s.handle+"|"+s.platform];});

return(<div style={{display:"flex",gap:0}}>
<div style={{flex:1,minWidth:0}}>
{/* FIX #29: Breadcrumb */}
<button onClick={function(){p.nav("programs");}} style={{background:"none",border:"none",color:"var(--t2)",fontSize:13,cursor:"pointer",marginBottom:16,fontFamily:"'DM Sans',sans-serif"}}>{"<-"} All Programs</button>
<div style={{marginBottom:20}}><div style={{display:"flex",alignItems:"center",gap:12,marginBottom:6}}><h1 style={{fontFamily:"'Instrument Serif',serif",fontSize:32,fontWeight:400}}>{p.prog.name}</h1>{scan?<span style={{fontSize:12,fontWeight:600,padding:"5px 12px",borderRadius:20,background:"var(--acg)",color:"var(--acl)"}}>Scanning...</span>:null}</div><span style={{color:"var(--t2)",fontSize:14}}>{tot} prospects{skCount>0?" ("+skCount+" skipped)":""}</span>{summary&&!scan?<span style={{color:"var(--t3)",fontSize:12,marginLeft:12}}>{summary}</span>:null}</div>
<div style={{display:"flex",gap:8,marginBottom:16,alignItems:"center",flexWrap:"wrap"}}>
{tot===0&&!scan?<button onClick={runScan} style={{...bS,background:"linear-gradient(135deg,var(--ac),#8b5cf6)",color:"#fff"}}>Start Scan with Claude</button>:<React.Fragment>
<div style={{display:"flex",gap:4,padding:4,background:"var(--bg2)",borderRadius:12,border:"1px solid var(--bd)"}}>{p.prog.platforms.map(function(pp){var a=aP===pp,c2=(pros[pp]||[]).length;return <button key={pp} onClick={function(){sAP(pp);sDetail(null);sSearch("");}} style={{display:"flex",alignItems:"center",gap:6,padding:"8px 14px",border:"none",borderRadius:8,background:a?"var(--bgi)":"transparent",color:a?"var(--t1)":"var(--t3)",fontSize:13,fontWeight:a?600:400,cursor:"pointer",fontFamily:"'DM Sans',sans-serif"}}>{PN[pp]}{c2>0?<span style={{fontSize:11,fontWeight:600,padding:"1px 6px",borderRadius:10,background:a?PC[pp]+"20":"var(--bd)",color:a?PC[pp]:"var(--t3)"}}>{c2}</span>:null}</button>;})}</div>
{/* FIX #13: Cancel or Rescan */}
{scan?<button onClick={cancelScan} style={{...bS,padding:"8px 14px",fontSize:13,background:"transparent",border:"1px solid var(--red)",color:"var(--red)"}}>Cancel</button>:<button onClick={runScan} style={{...bS,padding:"8px 14px",fontSize:13,background:"transparent",border:"1px solid var(--bd)",color:"var(--t2)"}}>Rescan</button>}
{/* FIX #11: Sort */}
<div style={{display:"flex",gap:4}}>{["score","followers","engagement","name"].map(function(s){return <button key={s} onClick={function(){sSort(s);}} style={{padding:"4px 8px",border:sortBy===s?"1px solid var(--ac)":"1px solid var(--bd)",borderRadius:6,background:sortBy===s?"var(--acg)":"transparent",color:sortBy===s?"var(--acl)":"var(--t3)",fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:"'DM Sans',sans-serif"}}>{s[0].toUpperCase()+s.slice(1)}</button>;})}</div>
{skCount>0?<button onClick={function(){sShowSk(!showSk);}} style={{fontSize:11,padding:"4px 10px",border:"1px solid var(--bd)",borderRadius:6,background:"transparent",color:"var(--t3)",cursor:"pointer",fontFamily:"'DM Sans',sans-serif"}}>{showSk?"Hide":"Show"} skipped</button>:null}
<div style={{marginLeft:"auto",display:"flex",gap:8,alignItems:"center"}}>{selCount>0?<span style={{fontSize:13,color:"var(--acl)",fontWeight:600}}>{selCount}</span>:null}{selDupes.length>0?<span style={{fontSize:12,color:"var(--org)"}}>({selDupes.length} cross-prog)</span>:null}<button onClick={function(){var s=getSelected();if(s.length>0)p.onOutreach(s);}} disabled={selCount===0} style={{...bS,padding:"8px 18px",fontSize:13,background:selCount>0?"linear-gradient(135deg,var(--ac),#8b5cf6)":"var(--bgi)",color:selCount>0?"#fff":"var(--t3)",cursor:selCount>0?"pointer":"not-allowed"}}>Outreach</button></div></React.Fragment>}</div>
{/* FIX #12: Search */}
{tot>0&&!scan?<div style={{marginBottom:12}}><input value={search} onChange={function(e){sSearch(e.target.value);}} placeholder="Search by name, handle, or niche..." style={{...iS,maxWidth:400}}/></div>:null}
{scan?<div style={{background:"var(--bg2)",border:"1px solid var(--bd)",borderRadius:14,padding:"16px 24px",marginBottom:16}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:10}}><span style={{fontSize:13,fontWeight:600}}>Claude Cowork working...</span><span style={{fontSize:13,fontWeight:600,color:"var(--acl)"}}>{Math.min(Math.round(pct),100)}%</span></div><div style={{height:4,background:"var(--bgi)",borderRadius:2,overflow:"hidden",marginBottom:12}}><div style={{height:"100%",width:Math.min(pct,100)+"%",background:"linear-gradient(90deg,var(--ac),var(--acl))",transition:"width .3s"}}/></div><div style={{display:"flex",flexDirection:"column",gap:6}}>{logs.map(function(l,i){return <div key={i} style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:6,height:6,borderRadius:"50%",background:l.c,flexShrink:0}}/><span style={{fontSize:12,color:"var(--t2)"}}>{l.msg}</span></div>;})}</div></div>:null}
{tot>0?<div style={{background:"var(--bg2)",border:"1px solid var(--bd)",borderRadius:14,overflow:"hidden"}}><div style={{display:"grid",gridTemplateColumns:"40px 2fr .8fr .7fr .7fr .5fr 50px",padding:"12px 20px",borderBottom:"1px solid var(--bd)",fontSize:11,fontWeight:600,textTransform:"uppercase",letterSpacing:".08em",color:"var(--t3)",alignItems:"center"}}><Ck on={allChecked} flip={toggleAll}/><span>Prospect</span><span>Followers</span><span>Eng.</span><span>Niche</span><span style={{textAlign:"center"}}>Score</span><span></span></div>
{cur.map(function(pr){var key=pr.handle+"|"+aP,ck=!!checked[key];var isSk=skipped[key];var dupe=otherO[key]||otherO[pr.handle+"|"+(pr.ap||aP)];var contacted=thisO[key]||thisO[pr.handle+"|"+(pr.ap||aP)];return(<div key={key} style={{display:"grid",gridTemplateColumns:"40px 2fr .8fr .7fr .7fr .5fr 50px",padding:"12px 20px",borderBottom:"1px solid var(--bd)",alignItems:"center",background:ck?"var(--acg)":isSk?"var(--bg0)":dupe?"rgba(240,160,48,.04)":"transparent",opacity:isSk?.5:1}} onMouseEnter={function(e){if(!ck&&!isSk)e.currentTarget.style.background=dupe?"rgba(240,160,48,.08)":"var(--bg3)";}} onMouseLeave={function(e){if(!ck&&!isSk)e.currentTarget.style.background=isSk?"var(--bg0)":dupe?"rgba(240,160,48,.04)":"transparent";}}>
<Ck on={ck} flip={function(){if(!isSk&&!contacted)sCk(function(prev){return{...prev,[key]:!prev[key]};});}}/>
<div style={{display:"flex",alignItems:"center",gap:10,cursor:"pointer"}} onClick={function(){sDetail(pr);}}>
<div style={{width:32,height:32,borderRadius:"50%",background:"linear-gradient(135deg,"+PC[aP]+"40,"+PC[aP]+"15)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:11,fontWeight:700,color:PC[aP],flexShrink:0}}>{pr.av}</div>
<div><div style={{display:"flex",alignItems:"center",gap:6}}><span style={{fontSize:13,fontWeight:600}}>{pr.name}</span>{pr.v?<span style={{color:"var(--blu)"}}>✓</span>:null}{pr.ap?<Tag color="#6366f1">Modash</Tag>:null}{dupe?<Tag color="var(--org)">In: {dupe.programName}</Tag>:null}{contacted?<Tag color="var(--blu)">Contacted</Tag>:null}</div><div style={{fontSize:11,color:"var(--t3)"}}>{pr.handle}</div></div></div>
<span style={{fontSize:13}}>{pr.fol}</span><span style={{fontSize:13,color:"var(--grn)"}}>{pr.eng}</span><span style={{fontSize:11,color:"var(--t2)"}}>{pr.niche}</span>
<div style={{textAlign:"center"}}><span style={{fontSize:14,fontWeight:700,color:pr.sc>=90?"var(--grn)":pr.sc>=80?"var(--acl)":"var(--t2)"}}>{pr.sc}</span></div>
<button onClick={function(e){e.stopPropagation();sSkipped(function(prev){return{...prev,[key]:!prev[key]};});sCk(function(prev){return{...prev,[key]:false};});}} style={{background:"none",border:"none",color:isSk?"var(--acl)":"var(--t3)",cursor:"pointer",fontSize:11,fontFamily:"'DM Sans',sans-serif"}}>{isSk?"undo":"skip"}</button>
</div>);})}</div>:!scan?<div style={{textAlign:"center",padding:"80px 20px",border:"1px dashed var(--bd)",borderRadius:16,background:"var(--bg2)"}}><h3 style={{fontSize:18,fontWeight:600,marginBottom:8}}>Ready to scan</h3></div>:null}
</div>
{/* FIX #15: Detail panel with actions */}
{detail?<div style={{width:340,flexShrink:0,borderLeft:"1px solid var(--bd)",background:"var(--bg1)",padding:24,position:"sticky",top:0,maxHeight:"100vh",overflowY:"auto"}}>
<div style={{display:"flex",justifyContent:"space-between",marginBottom:20}}><span style={{fontSize:11,fontWeight:600,textTransform:"uppercase",letterSpacing:".08em",color:"var(--t3)"}}>Detail</span><button onClick={function(){sDetail(null);}} style={{background:"none",border:"none",color:"var(--t3)",cursor:"pointer",fontSize:16}}>x</button></div>
<div style={{textAlign:"center",marginBottom:20}}><div style={{width:56,height:56,borderRadius:"50%",background:"linear-gradient(135deg,"+PC[aP]+"40,"+PC[aP]+"15)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:18,fontWeight:700,color:PC[aP],margin:"0 auto 12px"}}>{detail.av}</div><div style={{fontSize:18,fontWeight:600}}>{detail.name}</div><div style={{fontSize:13,color:"var(--t3)"}}>{detail.handle}</div>{detail.ap?<div style={{marginTop:6}}><Tag color="#6366f1">via Modash</Tag></div>:null}</div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:10,marginBottom:20}}>{[[detail.fol,"Followers"],[detail.eng,"Eng."],[detail.sc,"Score"]].map(function(x,i){return <div key={i} style={{textAlign:"center",padding:10,background:"var(--bg2)",borderRadius:8}}><div style={{fontSize:14,fontWeight:700}}>{x[0]}</div><div style={{fontSize:10,color:"var(--t3)"}}>{x[1]}</div></div>;})}</div>
{detail.rc&&detail.rc.length>0?<div style={{marginBottom:20}}><div style={{fontSize:11,fontWeight:600,color:"var(--t3)",marginBottom:8}}>RECENT CONTENT</div>{detail.rc.map(function(c2,i){return <div key={i} style={{fontSize:12,color:"var(--t2)",padding:"6px 0",borderBottom:i<detail.rc.length-1?"1px solid var(--bd)":"none"}}>{c2}</div>;})}</div>:null}
{/* FIX #15: Action buttons */}
<div style={{display:"flex",flexDirection:"column",gap:8}}>
<button onClick={function(){sCk(function(prev){return{...prev,[detail.handle+"|"+aP]:true};});sDetail(null);}} style={{...bS,padding:"10px",fontSize:13,background:"var(--acg)",color:"var(--acl)",border:"1px solid rgba(108,92,231,.3)",width:"100%"}}>Select for Outreach</button>
<a href={(PURL[detail.ap||aP]||"#")} target="_blank" rel="noopener noreferrer" style={{...bS,padding:"10px",fontSize:13,background:"transparent",color:"var(--t2)",border:"1px solid var(--bd)",width:"100%",textDecoration:"none",textAlign:"center",display:"block"}}>View on {PN[detail.ap||aP]}</a>
</div></div>:null}
</div>);}

// FIX #17,18,19,20: Compose with editable msgs, confirm, remove, mode-clear
function Compose(p){var _m=useState("ai_personalized"),mode=_m[0],sMode=_m[1];var _c=useState(p.isNudge?"Following up":""),ctx=_c[0],sCtx=_c[1];var _cu=useState(""),custom=_cu[0],sCustom=_cu[1];var _g=useState(false),gen=_g[0],sGen=_g[1];var _ms=useState({}),msgs=_ms[0],sMsgs=_ms[1];var _se=useState(false),sent=_se[0],sSent=_se[1];
var _confirm=useState(false),showConfirm=_confirm[0],sConfirm=_confirm[1];
var _removed=useState({}),removed=_removed[0],sRemoved=_removed[1];
var activeProspects=p.prospects.filter(function(_,i){return!removed[i];});
var hasTT=activeProspects.some(function(pr){return pr.platform==="tiktok";});
var dupes=[];if(!p.isNudge){activeProspects.forEach(function(pr){var m=p.allOutreach.find(function(o){return o.handle===pr.handle&&o.platform===pr.platform&&o.programId!==p.programId;});if(m)dupes.push({prospect:pr,prog:m.programName});});}
// FIX #20: Clear messages when switching modes
var switchMode=function(m){sMode(m);sMsgs({});};
var genMsgs=function(){sGen(true);setTimeout(function(){var m={};p.prospects.forEach(function(pr,i){if(removed[i])return;var fn=pr.name.split(" ")[0];var content=pr.rc&&pr.rc[0]?pr.rc[0].split("(")[0].trim():"your content";
if(mode==="ai_personalized")m[i]="Hey "+fn+"!\n\n"+(p.isNudge?"Circling back - ":"")+"Your \""+content+"\" really stood out.\n\n"+(ctx||"We'd love to partner.")+"\n\nThoughts?\n\nBest,\nJohn";
else if(mode==="ai_standard")m[i]="Hi "+fn+",\n\n"+(p.isNudge?"Following up. ":"")+"We think you'd be great for our program.\n\n"+(ctx||"Competitive commissions.")+"\n\nBest,\nJohn";
else m[i]=custom||"(Your message)";});sMsgs(m);sGen(false);},1500);};
var doSend=function(){sSent(true);setTimeout(function(){p.onSend(p.prospects.filter(function(_,i){return!removed[i];}).map(function(pr,i){var origIdx=p.prospects.indexOf(pr);var nm2={body:msgs[origIdx]||custom,sentAt:new Date().toLocaleString(),isNudge:p.isNudge};return{...pr,message:msgs[origIdx]||custom,messageHistory:(pr.messageHistory||[]).concat([nm2]),sentAt:new Date().toLocaleString(),replyStatus:"pending",nudgeCount:pr.nudgeCount||0,programId:p.programId,programName:p.programName,dealStage:pr.dealStage||"",notes:pr.notes||""};}));},2000);};
return(<div>
{/* FIX #18: Confirmation modal */}
<Modal show={showConfirm} title={"Send "+activeProspects.length+" message"+(activeProspects.length>1?"s":"")+"?"} body={"Claude will navigate your browser tabs and send each message through the platform's native UI. This cannot be undone."} confirmLabel={p.isNudge?"Send Nudges":"Send Messages"} onCancel={function(){sConfirm(false);}} onConfirm={function(){sConfirm(false);doSend();}}/>
<button onClick={p.onBack} style={{background:"none",border:"none",color:"var(--t2)",fontSize:13,cursor:"pointer",marginBottom:24,fontFamily:"'DM Sans',sans-serif"}}>{"<-"} {p.isNudge?"Back to Tracker":"Back to Discover"}</button>
<h1 style={{fontFamily:"'Instrument Serif',serif",fontSize:32,fontWeight:400,marginBottom:6}}>{p.isNudge?"Send Nudge":"Compose Outreach"}</h1><p style={{color:"var(--t2)",fontSize:14,marginBottom:20}}>{activeProspects.length} prospect{activeProspects.length>1?"s":""} for <strong>{p.programName}</strong></p>
{hasTT?<div style={{background:"rgba(255,0,80,.06)",border:"1px solid rgba(255,0,80,.2)",borderRadius:10,padding:14,marginBottom:12,fontSize:13,color:"var(--t2)"}}><strong style={{color:"#ff0050"}}>TikTok prospects</strong> — sent via Target Invite (commission + product form).</div>:null}
{dupes.length>0?<div style={{background:"rgba(255,107,107,.06)",border:"1px solid rgba(255,107,107,.25)",borderRadius:10,padding:14,marginBottom:12}}><div style={{fontSize:13,fontWeight:600,color:"var(--red)",marginBottom:4}}>Cross-Program Warning</div>{dupes.map(function(d,i){return <div key={i} style={{fontSize:12,color:"var(--t2)"}}>{d.prospect.name} — already in {d.prog}</div>;})}</div>:null}
<div style={{background:"var(--bg2)",border:"1px solid var(--bd)",borderRadius:16,padding:28,marginBottom:20}}><label style={lS}>Message Mode</label><div style={{display:"flex",gap:10,marginBottom:24}}>{[["ai_personalized","AI Personalized","Uses recent content"],["ai_standard","AI Standard","Same template"],["custom","Custom","Your message"]].map(function(x){return <div key={x[0]} onClick={function(){switchMode(x[0]);}} style={{flex:1,padding:14,borderRadius:12,border:mode===x[0]?"1px solid var(--ac)":"1px solid var(--bd)",background:mode===x[0]?"var(--acg)":"var(--bgi)",cursor:"pointer"}}><div style={{fontSize:13,fontWeight:600,color:mode===x[0]?"var(--acl)":"var(--t1)",marginBottom:4}}>{x[1]}</div><div style={{fontSize:11,color:"var(--t3)"}}>{x[2]}</div></div>;})}</div>
{mode!=="custom"?<div><label style={lS}>Context for AI</label><textarea value={ctx} onChange={function(e){sCtx(e.target.value);}} placeholder="e.g. 15% commission, free samples..." rows={3} style={{...iS,resize:"vertical",lineHeight:1.5}}/></div>:<div><label style={lS}>Your Message</label><textarea value={custom} onChange={function(e){sCustom(e.target.value);}} placeholder="Write your message..." rows={5} style={{...iS,resize:"vertical",lineHeight:1.5}}/></div>}
<button onClick={genMsgs} disabled={gen||(mode==="custom"&&!custom)||activeProspects.length===0} style={{...bS,marginTop:20,background:gen?"var(--bg3)":"linear-gradient(135deg,var(--ac),#8b5cf6)",color:"#fff"}}>{gen?"Generating...":mode==="custom"?"Preview":"Generate with AI"}</button></div>
{Object.keys(msgs).length>0&&activeProspects.length>0?<div style={{background:"var(--bg2)",border:"1px solid var(--bd)",borderRadius:16,padding:28}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}><div style={{fontSize:16,fontWeight:600}}>Previews ({activeProspects.length})</div>{!sent?<button onClick={function(){sConfirm(true);}} style={{...bS,padding:"10px 28px",background:"var(--grn)",color:"#000",fontWeight:700}}>{p.isNudge?"Send Nudges":"Send via Claude"}</button>:<Tag color="var(--grn)" bg="rgba(0,214,143,.15)">Sending...</Tag>}</div>
{p.prospects.map(function(pr,i){if(removed[i])return null;return <div key={i} style={{padding:16,background:"var(--bg0)",borderRadius:12,border:"1px solid var(--bd)",marginBottom:12}}>
<div style={{display:"flex",alignItems:"center",gap:10,marginBottom:8}}><span style={{fontSize:13,fontWeight:600}}>{pr.name}</span><span style={{marginLeft:"auto",fontSize:11,padding:"2px 8px",borderRadius:4,background:PC[pr.platform]+"15",color:PC[pr.platform]}}>{PN[pr.platform]}</span>
{/* FIX #19: Remove from batch */}
<button onClick={function(){sRemoved(function(prev){return{...prev,[i]:true};});}} style={{background:"none",border:"none",color:"var(--t3)",cursor:"pointer",fontSize:12,fontFamily:"'DM Sans',sans-serif"}}>remove</button></div>
{/* FIX #17: Editable message */}
<textarea value={msgs[i]||""} onChange={function(e){sMsgs(function(prev){return{...prev,[i]:e.target.value};});}} rows={6} style={{...iS,fontSize:12,lineHeight:1.6,resize:"vertical",width:"100%"}}/>
</div>;})}
</div>:null}</div>);}

// FIX #21,22,23,24,25: Tracker with status dropdown, nudge on no_reply, correct counts, debounced notes
function Tracker(p){var all=p.outreach;
var sent=all.length;var interested=all.filter(function(c){return c.replyStatus==="interested";}).length;var declined=all.filter(function(c){return c.replyStatus==="declined";}).length;var pend=all.filter(function(c){return c.replyStatus==="pending";}).length;var noReply=all.filter(function(c){return c.replyStatus==="no_reply";}).length;
var _so=useState("newest"),sortBy=_so[0],sSort=_so[1];var _ck=useState({}),checked=_ck[0],sCk=_ck[1];var _ta=useState("all"),tab=_ta[0],sTab=_ta[1];var _ex=useState(null),expanded=_ex[0],sExpanded=_ex[1];var _fp=useState("all"),filtProg=_fp[0],sFiltProg=_fp[1];
// FIX #25: Local notes state with debounce
var _localNotes=useState({}),localNotes=_localNotes[0],sLocalNotes=_localNotes[1];
var notesTimer=useRef(null);
useEffect(function(){return function(){if(notesTimer.current)clearTimeout(notesTimer.current);};},[]);
var handleNote=function(idx,val){sLocalNotes(function(prev){return{...prev,[idx]:val};});if(notesTimer.current)clearTimeout(notesTimer.current);notesTimer.current=setTimeout(function(){p.onChangeNotes(idx,val);},500);};
var progNames=[];all.forEach(function(o){if(o.programName&&progNames.indexOf(o.programName)===-1)progNames.push(o.programName);});
var sorted=all.map(function(c,i){return{...c,_i:i};});if(sortBy==="newest")sorted.reverse();if(sortBy==="name")sorted.sort(function(a,b){return a.name.localeCompare(b.name);});if(sortBy==="program")sorted.sort(function(a,b){return(a.programName||"").localeCompare(b.programName||"");});
var filtered=sorted.filter(function(c){return(tab==="all"||c.replyStatus===tab)&&(filtProg==="all"||c.programName===filtProg);});
// FIX #23: Allow nudge on pending AND no_reply
var selCount=Object.entries(checked).filter(function(e){return e[1]&&all[+e[0]]&&(all[+e[0]].replyStatus==="pending"||all[+e[0]].replyStatus==="no_reply");}).length;
var nudgeableVis=filtered.filter(function(c){return c.replyStatus==="pending"||c.replyStatus==="no_reply";});
var allNudgeCk=nudgeableVis.length>0&&nudgeableVis.every(function(c){return checked[c._i];});
return(<div><h1 style={{fontFamily:"'Instrument Serif',serif",fontSize:32,fontWeight:400,marginBottom:6}}>Outreach Tracker</h1><p style={{color:"var(--t2)",fontSize:14,marginBottom:20}}>{sent} messages across {progNames.length||0} program{progNames.length!==1?"s":""}</p>
<div style={{display:"flex",gap:12,marginBottom:24,flexWrap:"wrap"}}>{[["Sent",sent,"var(--ac)"],["Interested",interested,"var(--grn)"],["Pending",pend,"var(--org)"],["Declined",declined,"var(--red)"],["No Reply",noReply,"var(--t3)"],["Conversion",sent?Math.round(interested/sent*100)+"%":"—","var(--blu)"]].map(function(x,i){return <div key={i} style={{flex:"1 1 80px",padding:14,background:"var(--bg2)",border:"1px solid var(--bd)",borderRadius:14}}><div style={{fontSize:20,fontWeight:700,color:x[2]}}>{x[1]}</div><div style={{fontSize:11,color:"var(--t3)",marginTop:4}}>{x[0]}</div></div>;})}</div>
{all.length===0?<div style={{textAlign:"center",padding:"60px 20px",border:"1px dashed var(--bd)",borderRadius:16,background:"var(--bg2)"}}><p style={{color:"var(--t3)",fontSize:14}}>No outreach yet.</p></div>:<div>
<div style={{display:"flex",gap:8,marginBottom:16,alignItems:"center",flexWrap:"wrap"}}>
<div style={{display:"flex",gap:4,padding:4,background:"var(--bg2)",borderRadius:10,border:"1px solid var(--bd)"}}>{[["all","All"],["pending","Pending"],["interested","Interested"],["declined","Declined"],["no_reply","No Reply"]].map(function(x){return <button key={x[0]} onClick={function(){sTab(x[0]);}} style={{padding:"5px 10px",border:"none",borderRadius:7,background:tab===x[0]?"var(--bgi)":"transparent",color:tab===x[0]?"var(--t1)":"var(--t3)",fontSize:11,fontWeight:tab===x[0]?600:400,cursor:"pointer",fontFamily:"'DM Sans',sans-serif"}}>{x[1]}</button>;})}</div>
{progNames.length>1?<select value={filtProg} onChange={function(e){sFiltProg(e.target.value);}} style={{...iS,width:"auto",padding:"5px 10px",fontSize:11}}><option value="all">All Programs</option>{progNames.map(function(n){return <option key={n} value={n}>{n}</option>;})}</select>:null}
<div style={{display:"flex",gap:4}}>{["newest","oldest","name","program"].map(function(s){return <button key={s} onClick={function(){sSort(s);}} style={{padding:"4px 8px",border:sortBy===s?"1px solid var(--ac)":"1px solid var(--bd)",borderRadius:6,background:sortBy===s?"var(--acg)":"transparent",color:sortBy===s?"var(--acl)":"var(--t3)",fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:"'DM Sans',sans-serif"}}>{s[0].toUpperCase()+s.slice(1)}</button>;})}</div>
<div style={{marginLeft:"auto",display:"flex",gap:8,alignItems:"center"}}>{selCount>0?<span style={{fontSize:12,color:"var(--org)",fontWeight:600}}>{selCount}</span>:null}<button onClick={function(){var s=Object.entries(checked).filter(function(e){return e[1]&&all[+e[0]]&&(all[+e[0]].replyStatus==="pending"||all[+e[0]].replyStatus==="no_reply");}).map(function(e){return all[+e[0]];});if(s.length>0)p.onNudge(s);}} disabled={selCount===0} style={{...bS,padding:"6px 14px",fontSize:12,background:selCount>0?"linear-gradient(135deg,var(--org),#e8832a)":"var(--bgi)",color:selCount>0?"#fff":"var(--t3)",cursor:selCount>0?"pointer":"not-allowed"}}>Nudge</button></div></div>
<div style={{background:"var(--bg2)",border:"1px solid var(--bd)",borderRadius:14,overflow:"hidden"}}><div style={{display:"grid",gridTemplateColumns:"36px 1.6fr .7fr .6fr .7fr .5fr .4fr",padding:"10px 20px",borderBottom:"1px solid var(--bd)",fontSize:10,fontWeight:600,textTransform:"uppercase",letterSpacing:".08em",color:"var(--t3)",alignItems:"center"}}><Ck on={allNudgeCk} flip={function(){var next={...checked};nudgeableVis.forEach(function(c){next[c._i]=!allNudgeCk;});sCk(next);}}/><span>Prospect</span><span>Program</span><span>Platform</span><span>Status</span><span>Nudges</span><span></span></div>
{filtered.map(function(c){var isNudgeable=c.replyStatus==="pending"||c.replyStatus==="no_reply";var ck=!!checked[c._i]&&isNudgeable;var isExp=expanded===c._i;var hist=c.messageHistory||[];var stCfg=ST[c.replyStatus]||ST.pending;
return(<React.Fragment key={c._i}>
<div style={{display:"grid",gridTemplateColumns:"36px 1.6fr .7fr .6fr .7fr .5fr .4fr",padding:"10px 20px",borderBottom:isExp?"none":"1px solid var(--bd)",alignItems:"center",background:isExp?"var(--bg3)":ck?"rgba(240,160,48,.06)":"transparent",cursor:"pointer"}} onClick={function(){sExpanded(isExp?null:c._i);}} onMouseEnter={function(e){if(!ck&&!isExp)e.currentTarget.style.background="var(--bg3)";}} onMouseLeave={function(e){if(!ck&&!isExp)e.currentTarget.style.background="transparent";}}>
{isNudgeable?<Ck on={ck} flip={function(){sCk(function(prev){return{...prev,[c._i]:!prev[c._i]};});}}/>:<div style={{width:18}}/>}
<div style={{display:"flex",alignItems:"center",gap:10}}><div style={{width:28,height:28,borderRadius:"50%",background:"linear-gradient(135deg,"+PC[c.platform]+"40,"+PC[c.platform]+"15)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:10,fontWeight:700,color:PC[c.platform]}}>{c.av}</div><div><div style={{fontSize:13,fontWeight:600}}>{c.name}</div><div style={{fontSize:11,color:"var(--t3)"}}>{c.handle}</div></div></div>
<span style={{fontSize:12,color:"var(--acl)",fontWeight:500}}>{c.programName||"—"}</span>
<span style={{fontSize:12,color:PC[c.platform],fontWeight:500}}>{PN[c.platform]}</span>
{/* FIX #21,22: Status dropdown instead of cycle */}
<select value={c.replyStatus} onClick={function(e){e.stopPropagation();}} onChange={function(e){e.stopPropagation();p.onChangeStatus(c._i,e.target.value);}} style={{padding:"3px 6px",fontSize:11,fontWeight:600,border:"1px solid "+(stCfg.c==="var(--t3)"?"var(--bd)":stCfg.c),borderRadius:6,background:stCfg.bg,color:stCfg.c,cursor:"pointer",fontFamily:"'DM Sans',sans-serif",appearance:"auto"}}>
<option value="pending">Pending</option><option value="interested">Interested</option><option value="declined">Declined</option><option value="no_reply">No Reply</option></select>
<div style={{textAlign:"center"}}>{(c.nudgeCount||0)>0?<span style={{fontSize:13,fontWeight:700,color:"var(--org)"}}>{c.nudgeCount}</span>:<span style={{color:"var(--t3)"}}>—</span>}</div>
<div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:4}}>
{isNudgeable?<button onClick={function(e){e.stopPropagation();p.onNudge([c]);}} style={{fontSize:10,padding:"3px 6px",borderRadius:4,border:"1px solid var(--org)",background:"rgba(240,160,48,.06)",color:"var(--org)",cursor:"pointer",fontFamily:"'DM Sans',sans-serif",fontWeight:600}}>Nudge</button>:null}
<span style={{fontSize:14,color:"var(--t3)",transform:isExp?"rotate(180deg)":"rotate(0)",transition:"transform .2s",display:"inline-block"}}>&#9662;</span></div></div>
{isExp?<div style={{padding:"12px 20px 16px 56px",borderBottom:"1px solid var(--bd)",background:"var(--bg3)"}}>
{c.replyStatus==="interested"?<div style={{display:"flex",gap:6,marginBottom:14}}>{STAGES.map(function(s){var active=c.dealStage===s||(s==="interested"&&c.replyStatus==="interested"&&!c.dealStage);return <button key={s} onClick={function(e){e.stopPropagation();p.onChangeDealStage(c._i,s);}} style={{padding:"4px 10px",borderRadius:6,fontSize:11,fontWeight:600,border:"1px solid "+(active?STAGE_C[s]:"var(--bd)"),background:active?STAGE_C[s]+"18":"transparent",color:active?STAGE_C[s]:"var(--t3)",cursor:"pointer",fontFamily:"'DM Sans',sans-serif"}}>{STAGE_L[s]}</button>;})}</div>:null}
<div style={{fontSize:11,fontWeight:600,color:"var(--t3)",textTransform:"uppercase",letterSpacing:".08em",marginBottom:8}}>Messages ({hist.length})</div>
{hist.length>0?<div style={{display:"flex",flexDirection:"column",gap:8,marginBottom:14}}>{hist.map(function(m,mi){return <div key={mi} style={{background:"var(--bgi)",borderRadius:8,border:"1px solid var(--bd)",padding:12}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}><Tag color={m.isNudge?"var(--org)":"var(--ac)"}>{m.isNudge?"Nudge":"Initial"}</Tag><span style={{fontSize:10,color:"var(--t3)"}}>{m.sentAt}</span></div><pre style={{fontSize:12,color:"var(--t2)",lineHeight:1.5,whiteSpace:"pre-wrap",fontFamily:"'DM Sans',sans-serif",margin:0}}>{m.body}</pre></div>;})}</div>:<p style={{fontSize:12,color:"var(--t3)",marginBottom:14}}>No messages</p>}
<div style={{fontSize:11,fontWeight:600,color:"var(--t3)",textTransform:"uppercase",letterSpacing:".08em",marginBottom:6}}>Notes</div>
{/* FIX #25: Debounced notes */}
<textarea value={localNotes[c._i]!==undefined?localNotes[c._i]:(c.notes||"")} onClick={function(e){e.stopPropagation();}} onChange={function(e){e.stopPropagation();handleNote(c._i,e.target.value);}} placeholder="Add notes..." rows={2} style={{...iS,fontSize:12,resize:"vertical"}}/>
</div>:null}
</React.Fragment>);})}</div></div>}</div>);}

export default function App(){
var _pg=useState("login"),pg=_pg[0],sPg=_pg[1];var _pr=useState([]),progs=_pr[0],sProgs=_pr[1];var _se=useState(null),sel=_se[0],sSel=_se[1];var _mk=useState(false),mk=_mk[0],sMk=_mk[1];var _nv=useState("programs"),nv=_nv[0],sNv=_nv[1];var _ss=useState({tiktok:false,instagram:false,facebook:false,modash:false}),sess=_ss[0],sSess=_ss[1];var _op=useState(null),outP=_op[0],sOutP=_op[1];var _np=useState(null),nudgeP=_np[0],sNudgeP=_np[1];var _or=useState([]),outreach=_or[0],sOutreach=_or[1];
// FIX #26: Cowork detection toggle
var _cw=useState(true),coworkOn=_cw[0],sCw=_cw[1];
var togSess=function(id){sSess(function(prev){return{...prev,[id]:!prev[id]};});};
var go=function(t,i){sMk(false);sOutP(null);sNudgeP(null);sNv(t);if(t==="programs")sSel(null);else if(t==="discover"&&i!==undefined)sSel(i);else if(t==="discover"&&i===undefined&&sel===null&&progs.length>0)sSel(0);};
var handleSend=function(msgs){sOutreach(function(prev){return prev.concat(msgs);});if(sel!==null)sProgs(function(prev){var next=[...prev];if(next[sel])next[sel]={...next[sel],contacted:next[sel].contacted+msgs.length};return next;});sOutP(null);sNv("outreach");};
var handleNudgeSend=function(nudged){sOutreach(function(prev){var next=[...prev];nudged.forEach(function(np){var idx=next.findIndex(function(o){return o.handle===np.handle&&o.platform===np.platform&&o.programId===np.programId;});if(idx>=0)next[idx]={...next[idx],nudgeCount:(next[idx].nudgeCount||0)+1,replyStatus:"pending",message:np.message,messageHistory:np.messageHistory||next[idx].messageHistory||[],sentAt:np.sentAt};else next.push(np);});return next;});sNudgeP(null);sNv("outreach");};
// FIX #24: Correct interested count increment/decrement
var changeStatus=function(idx,newStatus){sOutreach(function(prev){var next=[...prev];var old=next[idx].replyStatus;next[idx]={...next[idx],replyStatus:newStatus};if(newStatus!=="interested")next[idx].dealStage="";
sProgs(function(pp){var u=[...pp];var pi=u.findIndex(function(pr){return pr.id===next[idx].programId;});if(pi>=0){var int=u[pi].interested||0;if(old==="interested"&&newStatus!=="interested")int=Math.max(0,int-1);if(old!=="interested"&&newStatus==="interested")int=int+1;u[pi]={...u[pi],interested:int};}return u;});
return next;});};
var changeDealStage=function(idx,stage){sOutreach(function(prev){var next=[...prev];next[idx]={...next[idx],dealStage:stage};return next;});};
var changeNotes=function(idx,notes){sOutreach(function(prev){var next=[...prev];next[idx]={...next[idx],notes:notes};return next;});};
var deleteProgram=function(i){var pid=progs[i]?progs[i].id:null;var next=[...progs];next.splice(i,1);sProgs(next);if(pid)sOutreach(function(prev){return prev.filter(function(o){return o.programId!==pid;});});if(sel===i){sSel(null);sNv("programs");}else if(sel!==null&&sel>i)sSel(sel-1);};
// FIX #27: Logout
if(pg==="login")return <React.Fragment><style>{CSS}</style><Login onIn={function(){sPg("d");}}/></React.Fragment>;
var v=nudgeP?"nudge":outP?"compose":mk?"create":nv==="sessions"?"sessions":nv==="outreach"?"outreach":sel!==null&&nv==="discover"?"discover":"programs";
var curProg=sel!==null?progs[sel]:null;
return(<React.Fragment><style>{CSS}</style><div style={{display:"flex",minHeight:"100vh"}}><Side pg={v==="create"||v==="compose"||v==="nudge"?"programs":v==="outreach"?"outreach":v} nav={go} progs={progs} sel={sel} sess={sess} outreach={outreach} coworkOn={coworkOn} onLogout={function(){sPg("login");sProgs([]);sSel(null);sOutreach([]);sNv("programs");sMk(false);sOutP(null);sNudgeP(null);sSess({tiktok:false,instagram:false,facebook:false,modash:false});}}/>
<div style={{marginLeft:240,flex:1,padding:"36px 48px",position:"relative",zIndex:1}}>
{v==="programs"?<Progs progs={progs} sess={sess} onCreate={function(){sMk(true);sNv("programs");}} onSel={function(i){sSel(i);sNv("discover");}} onDelete={deleteProgram} nav={go}/>:null}
{v==="create"?<Crt sess={sess} onSave={function(d){sProgs(function(prev){return prev.concat([d]);});sSel(progs.length);sMk(false);sNv("discover");}} onCancel={function(){sMk(false);}}/>:null}
{v==="discover"&&curProg?<Disc prog={curProg} allOutreach={outreach} onOutreach={function(s){sOutP(s);}} onProspectsFound={function(n){sProgs(function(prev){var next=[...prev];if(next[sel])next[sel]={...next[sel],prospects:n};return next;});}} nav={go}/>:null}
{v==="compose"&&outP?<Compose prospects={outP} allOutreach={outreach} programId={curProg?curProg.id:""} programName={curProg?curProg.name:""} onBack={function(){sOutP(null);}} onSend={handleSend} isNudge={false}/>:null}
{v==="nudge"&&nudgeP?<Compose prospects={nudgeP} allOutreach={outreach} programId={nudgeP[0]?nudgeP[0].programId:""} programName={nudgeP[0]?nudgeP[0].programName:""} onBack={function(){sNudgeP(null);}} onSend={handleNudgeSend} isNudge={true}/>:null}
{v==="outreach"?<Tracker outreach={outreach} onNudge={function(s){sNudgeP(s);}} onChangeStatus={changeStatus} onChangeDealStage={changeDealStage} onChangeNotes={changeNotes}/>:null}
{v==="sessions"?<Sessions sess={sess} toggle={togSess}/>:null}
</div></div></React.Fragment>);}
